val sampleText = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus scelerisque condimentum tellus ut maximus. Duis semper blandit massa, vel placerat libero pellentesque ut. Pellentesque non sapien non libero egestas egestas. Donec placerat placerat metus, ut consequat mi sagittis in. Maecenas mauris nibh, posuere sit amet magna pharetra, volutpat posuere urna. Aliquam erat volutpat. Fusce feugiat ex ut augue tempus, quis ullamcorper nisi faucibus. Sed in accumsan dolor. In sed lectus lacus. Quisque diam lorem, eleifend vel dui in, placerat ultrices velit. Nunc nulla odio, lacinia pulvinar lacus in, congue consequat augue. Sed in nulla neque. Donec rhoncus ex augue, et facilisis lacus mattis a. Fusce sit amet turpis urna. Suspendisse est dolor, congue vitae diam vitae, vulputate placerat dolor. Vestibulum feugiat magna nisl.

Nullam ac suscipit elit, eget fringilla diam. Praesent pharetra libero sed turpis vehicula lacinia. Morbi et diam eget nunc bibendum vestibulum vitae a nunc. Vivamus in justo congue metus posuere tristique in eu ipsum. Duis accumsan eros in nulla porttitor ornare vel at tortor. In hac habitasse platea dictumst. Phasellus non arcu ut felis ornare laoreet vel at risus. Suspendisse eget felis vel nulla mollis tempor. Etiam cursus sem eget metus pulvinar ornare. Vestibulum at sapien non ipsum laoreet tincidunt. Vivamus accumsan iaculis lorem sed malesuada. Aliquam velit dui, volutpat ut turpis sagittis, euismod egestas metus.

Morbi iaculis neque sed dolor pretium blandit. Mauris quis ipsum lectus. In turpis mi, porttitor vitae tellus pretium, pharetra convallis ante. Maecenas vitae ullamcorper quam, in hendrerit tellus. Donec tempor ornare lacinia. In lobortis vitae metus at tincidunt. Donec eget neque aliquam, facilisis nisi sit amet, faucibus tortor. Nulla commodo tincidunt sapien sollicitudin tristique.

Pellentesque tempor magna sed lacinia consectetur. Proin sagittis semper nisi, ac consequat nisi ornare vitae. Duis at diam cursus, dictum quam a, lacinia sapien. Proin sit amet dictum ante. Nam non ex eget sapien molestie commodo. Sed mattis ac neque ac iaculis. Morbi semper sem et nibh placerat scelerisque. Vivamus vestibulum lectus sapien, nec mollis lacus varius eget. Nullam gravida nunc quis purus imperdiet faucibus. Nulla at metus eu erat dictum interdum et in nulla. Vestibulum tempus arcu vitae arcu ullamcorper, et ornare tellus auctor. Ut gravida, felis id vulputate tincidunt, sem ligula euismod sapien, at vulputate augue leo vitae urna. Mauris volutpat quam vitae bibendum vestibulum. Etiam ut nibh id sem maximus tempus.

Donec tempus luctus rhoncus. Pellentesque feugiat tellus eget dui rhoncus, quis faucibus urna malesuada. Donec scelerisque nisl non odio hendrerit, ac tincidunt enim dapibus. Aliquam dui magna, volutpat non diam in, vehicula dapibus enim. Sed in convallis leo. Integer ex quam, convallis non urna varius, tincidunt rutrum sem. Morbi massa urna, eleifend at posuere et, hendrerit ac augue.
""".trimIndent()
